runtime: nodejs20 # Or a suitable Node.js version
instance_class: F1 # Choose an appropriate instance class

network:
  instance_tag: mylaps-server # Optional: Add a tag for firewall rules


handlers:
- url: /.*
  script: 'server.js'

env_variables:
  # Add any environment variables you need here
